### ISSUE TITLE
Reset function

### ISSUE THREAD

**Issue by chetto1983** [leomil72/leOS2#2]
Reset function don't work on arduino yun

**Comment by leomil72** [comment]
leOS2 only runs on the AVR8 MCUs like the ATmega32U4 that is installed on the Yun. But the Yun has also a SoC from Atheros where a Linux distro is running. You can just reset the Atmel MCU but not the SoC. To reset the SoC you have to consider that you have a real SO so you should try to use some Linux commands to try to reset the SoC (try "sudo shutdown -r now" but I don't know the Linux distro that runs on the Yun so I don't know if you can write such command).

**Comment by chetto1983** [comment]
Ciao Leo,

Lo so che resetta solo il microprocessore.

Ma il problema è che non lo resetta ma lo pianta.

Inviato da iPhone

**Comment by leomil72** [comment]
Sulla Leonardo, che monta la stessa MCU, la funzione di reset... funziona. Sfortunatamente non ho una Yun per provare, non so se cambia qualcosa per via dell'interconnessione MCU/SoC.

**Comment by Aqvic** [comment]
Hello Leonardo! Thank you for amazing leOS.
I have some warnings under the Linux Arduino IDE:
`In file included from /home/user/Arduino/libraries/leOS2/examples/leOS2_2_tasks/leOS2_2_tasks.ino:28:0:
/home/user/Arduino/libraries/leOS2/leOS2.h:82:75: warning: converting to non-pointer type 'uint8_t {aka unsigned char}' from NULL [-Wconversion-null]
   uint8_t modifyTask(void (*)(void), unsigned long, uint8_t oneTimeTask = NULL);
                                                                           ^
/home/user/Arduino/libraries/leOS2/leOS2.h:91:79: warning: converting to non-pointer type 'long unsigned int' from NULL [-Wconversion-null]
         uint8_t setTask(void (*)(void), uint8_t, unsigned long taskInterval = NULL);
                                                                               ^
In file included from /home/user/Arduino/libraries/leOS2/leOS2.cpp:7:0:
/home/user/Arduino/libraries/leOS2/leOS2.h:82:75: warning: converting to non-pointer type 'uint8_t {aka unsigned char}' from NULL [-Wconversion-null]
   uint8_t modifyTask(void (*)(void), unsigned long, uint8_t oneTimeTask = NULL);
                                                                           ^
/home/user/Arduino/libraries/leOS2/leOS2.h:91:79: warning: converting to non-pointer type 'long unsigned int' from NULL [-Wconversion-null]
         uint8_t setTask(void (*)(void), uint8_t, unsigned long taskInterval = NULL);
                                                                               ^
/home/user/Arduino/libraries/leOS2/leOS2.cpp: In member function 'uint8_t leOS2::pauseTask(void (*)())':
/home/user/Arduino/libraries/leOS2/leOS2.cpp:87:32: warning: converting to non-pointer type 'long unsigned int' from NULL [-Wconversion-null]
     return (setTask(userTask, 0));
                                ^
/home/user/Arduino/libraries/leOS2/leOS2.cpp: In member function 'uint8_t leOS2::restartTask(void (*)())':
/home/user/Arduino/libraries/leOS2/leOS2.cpp:93:32: warning: converting to non-pointer type 'long unsigned int' from NULL [-Wconversion-null]
     return (setTask(userTask, 1));
                                ^
/home/user/Arduino/libraries/leOS2/leOS2.cpp: In member function 'uint8_t leOS2::modifyTask(void (*)(), long unsigned int, uint8_t)':
/home/user/Arduino/libraries/leOS2/leOS2.cpp:100:15: warning: converting to non-pointer type 'uint8_t {aka unsigned char}' from NULL [-Wconversion-null]
   oneTimeTask = NULL;
               ^
/home/user/Arduino/libraries/leOS2/leOS2.cpp:114:23: warning: NULL used in arithmetic [-Wpointer-arith]
    if (oneTimeTask != NULL) {
                       ^
/home/user/Arduino/libraries/leOS2/leOS2.cpp: In member function 'uint8_t leOS2::setTask(void (*)(), uint8_t, long unsigned int)':
/home/user/Arduino/libraries/leOS2/leOS2.cpp:141:25: warning: NULL used in arithmetic [-Wpointer-arith]
     if (taskInterval == NULL) {`

**Comment by leomil72** [comment]
Chiuso per mancanza di nuove info.
