### ISSUE TITLE
Task 0 always executes

### ISSUE THREAD

**Issue by majenkotech** [leomil72/leOS2#3]
If you create one task as a ONETIME task and have no other tasks registered the ONETIME task constantly executes in a loop.

This is because the task scheduler portion uses `do ... while` instead of `while ...` which means that task 0 will always be executed *before* the test that determines if there are any tasks in the list.

**Comment by leomil72** [comment]
I've done a little bit of chaos while accepting your commit, because I changed the code locally without first synchronizing the repo with the remote git server. Ok, now it's been integrated into the code.
