### ISSUE TITLE
Warnings under the Linux

### ISSUE THREAD

**Issue by Aqvic** [leomil72/leOS2#5]
Hello Leonardo! Thank you for amazing leOS.
I have some warnings under the Linux Arduino IDE:
`In file included from /home/user/Arduino/libraries/leOS2/examples/leOS2_2_tasks/leOS2_2_tasks.ino:28:0: /home/user/Arduino/libraries/leOS2/leOS2.h:82:75: warning: converting to non-pointer type 'uint8_t {aka unsigned char}' from NULL [-Wconversion-null] uint8_t modifyTask(void (*)(void), unsigned long, uint8_t oneTimeTask = NULL); ^ /home/user/Arduino/libraries/leOS2/leOS2.h:91:79: warning: converting to non-pointer type 'long unsigned int' from NULL [-Wconversion-null] uint8_t setTask(void (*)(void), uint8_t, unsigned long taskInterval = NULL); ^ In file included from /home/user/Arduino/libraries/leOS2/leOS2.cpp:7:0: /home/user/Arduino/libraries/leOS2/leOS2.h:82:75: warning: converting to non-pointer type 'uint8_t {aka unsigned char}' from NULL [-Wconversion-null] uint8_t modifyTask(void (*)(void), unsigned long, uint8_t oneTimeTask = NULL); ^ /home/user/Arduino/libraries/leOS2/leOS2.h:91:79: warning: converting to non-pointer type 'long unsigned int' from NULL [-Wconversion-null] uint8_t setTask(void (*)(void), uint8_t, unsigned long taskInterval = NULL); ^ /home/user/Arduino/libraries/leOS2/leOS2.cpp: In member function 'uint8_t leOS2::pauseTask(void (*)())': /home/user/Arduino/libraries/leOS2/leOS2.cpp:87:32: warning: converting to non-pointer type 'long unsigned int' from NULL [-Wconversion-null] return (setTask(userTask, 0)); ^ /home/user/Arduino/libraries/leOS2/leOS2.cpp: In member function 'uint8_t leOS2::restartTask(void (*)())': /home/user/Arduino/libraries/leOS2/leOS2.cpp:93:32: warning: converting to non-pointer type 'long unsigned int' from NULL [-Wconversion-null] return (setTask(userTask, 1)); ^ /home/user/Arduino/libraries/leOS2/leOS2.cpp: In member function 'uint8_t leOS2::modifyTask(void (*)(), long unsigned int, uint8_t)': /home/user/Arduino/libraries/leOS2/leOS2.cpp:100:15: warning: converting to non-pointer type 'uint8_t {aka unsigned char}' from NULL [-Wconversion-null] oneTimeTask = NULL; ^ /home/user/Arduino/libraries/leOS2/leOS2.cpp:114:23: warning: NULL used in arithmetic [-Wpointer-arith] if (oneTimeTask != NULL) { ^ /home/user/Arduino/libraries/leOS2/leOS2.cpp: In member function 'uint8_t leOS2::setTask(void (*)(), uint8_t, long unsigned int)': /home/user/Arduino/libraries/leOS2/leOS2.cpp:141:25: warning: NULL used in arithmetic [-Wpointer-arith] if (taskInterval == NULL) {`

**Comment by leomil72** [comment]
Fixed. I've published new release 2.3.2. In a couple of days it should be available from the IDE's Library manager too.
